#!/usr/bin/env bash

# changes the user email for all commits
#
# Usage:
#    git-change-email <user-to-search> <new-email>
#
f() {
  git filter-branch --commit-filter "
    if [ \"\$GIT_COMMITTER_NAME\" = \"$1\" ];
    then
            GIT_COMMITTER_NAME=\"$1\";
            GIT_AUTHOR_NAME=\"$1\";
            GIT_COMMITTER_EMAIL=\"$2\";
            GIT_AUTHOR_EMAIL=\"$2\";
            git commit-tree \"\$@\";
    else
            git commit-tree \"\$@\";
    fi" HEAD
}

OFF='\033[0m'
RED='\033[0;31m'

if [[ $# -lt 2 ]]; then
  echo -e "${RED}Wrong number of params!$OFF"
  echo -e "Usage: git-change-email <user-to-search> <new-email>"
  exit 1
fi

f "$@"
